# Generated by Django 2.2.1 on 2019-05-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingChallenge', '0002_auto_20190529_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('agility', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('vitality', models.IntegerField()),
                ('katana', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
